"""Generates the Obsidian side of the vault from the index.

Every event note and category note is fully derived from the index, except the
free-form area below the END_MARKER line, which is preserved across
regeneration. `rebuild_all()` recreates every note, so the vault can always be
rebuilt from `.xolitical/` (e.g. after a git merge).
"""

import json
import os
import re
from pathlib import Path

END_MARKER = "%% xolitical:end"
END_LINE = (f"{END_MARKER} — write below this line; it is kept when this note is "
            "regenerated by the Xolitical viewer %%")

EVENTS_DIR = "Events"
CATEGORIES_DIR = "Categories"
MEDIA_DIR = "_media"

ID_RE = re.compile(r"^xolitical_(id|category):\s*(\S+)\s*$", re.M)
BAD_CHARS = re.compile(r'[\\/:*?"<>|#^\[\]]+')
TAG_RE = re.compile(r"[^a-z0-9_/-]+")


def yaml_str(s):
    """JSON string literals are valid YAML scalars — free correct escaping."""
    return json.dumps(s or "", ensure_ascii=False)


def safe_name(s, limit=120):
    s = BAD_CHARS.sub(" ", s or "")
    s = " ".join(s.split()).strip(" .")
    return (s[:limit].rstrip(" .")) or "untitled"


def norm_tag(t):
    t = TAG_RE.sub("-", (t or "").strip().lower().replace(" ", "-")).strip("-/")
    return re.sub(r"-{2,}", "-", t)


def yaml_list(key, values):
    if not values:
        return [f"{key}: []"]
    return [f"{key}:"] + [f"  - {yaml_str(v)}" for v in values]


def read_tail(path: Path):
    """User-written text below the end marker (empty if none)."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return ""
    i = text.find(END_MARKER)
    if i < 0:
        return ""
    nl = text.find("\n", i)
    return "" if nl < 0 else text[nl + 1:]


def write_text(path: Path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8", newline="\n")
    os.replace(tmp, path)


class VaultGen:
    def __init__(self, vault: Path, index):
        self.vault = vault
        self.index = index
        self.note_paths = {}  # xolitical id -> vault-relative path of its note (as found on disk)
        # Names in filenames are capped at 80 chars (the full name always stays in the
        # note). Only for unusually deep vault folders (> ~115 chars) is the cap lowered
        # further, to stay under Windows' 260-char path limit.
        self.name_budget = max(24, min(80, 240 - len(str(vault)) - 45))
        self.scan_notes()

    # ------------------------------------------------------------ discovery
    def scan_notes(self):
        self.note_paths = {}
        for folder in (EVENTS_DIR, CATEGORIES_DIR):
            base = self.vault / folder
            if not base.is_dir():
                continue
            for p in base.rglob("*.md"):
                try:
                    with open(p, encoding="utf-8") as f:
                        head = f.read(800)
                except OSError:
                    continue
                m = ID_RE.search(head)
                if m:
                    self.note_paths[m.group(2)] = p.relative_to(self.vault).as_posix()

    # ----------------------------------------------------------- categories
    def category_path(self, cid):
        """Vault-relative path (no .md) of a category or subcategory note."""
        c = self.index.category(cid)
        if not c:
            return None
        if c["parent"]:
            parent = self.category_path(c["parent"])
            return f"{parent}/{safe_name(c['name'], self.name_budget)}" if parent else None
        return f"{CATEGORIES_DIR}/{safe_name(c['name'], self.name_budget)}"

    def category_link(self, cid):
        c = self.index.category(cid)
        return f"[[{self.category_path(cid)}|{c['name']}]]"

    def render_category(self, cid):
        c = self.index.category(cid)
        lines = ["---", f"xolitical_category: {cid}"]
        if c["parent"]:
            lines.append(f"parent: {yaml_str(self.category_link(c['parent']))}")
        lines += ["---", f"# {c['name']}", ""]
        if c["parent"]:
            lines.append(f"Subcategory of {self.category_link(c['parent'])}.")
            lines.append("")
        else:
            subs = sorted((self.index.category(k) for k in self.index.children(cid)),
                          key=lambda x: x["name"].lower())
            if subs:
                lines.append("**Subcategories:** " + " · ".join(self.category_link(s["id"]) for s in subs))
                lines.append("")
        lines += ["![[Category.base]]", "", END_LINE, ""]
        return "\n".join(lines)

    def write_category(self, cid):
        rel = self.category_path(cid) + ".md"
        old = self.note_paths.get(cid)
        tail = read_tail(self.vault / (old or rel))
        write_text(self.vault / rel, self.render_category(cid) + tail)
        if old and old != rel:
            self._remove(old)
            self.rewrite_links(old[:-3], rel[:-3])
        self.note_paths[cid] = rel

    def remove_note(self, xid):
        old = self.note_paths.pop(xid, None)
        if old:
            self._remove(old)

    def _remove(self, rel):
        p = self.vault / rel
        try:
            p.unlink()
        except FileNotFoundError:
            pass
        # prune now-empty folders up to the top-level Events/Categories dir
        d = p.parent
        while d != self.vault and d.name not in (EVENTS_DIR, CATEGORIES_DIR):
            try:
                d.rmdir()
            except OSError:
                break
            d = d.parent

    # ---------------------------------------------------------------- events
    def event_paths(self):
        """Deterministic note path for every event.

        `Events/<YYYY>/<YYYY-MM-DD> <name>.md`. If two events would share a path,
        the earliest-created keeps it and later ones get their short id appended.
        """
        groups = {}
        for eid, (name, created, date) in self.index.event_dates().items():
            year = date[:4] if len(date) >= 4 else "undated"
            short = safe_name(name, self.name_budget)
            stem = f"{date} {short}" if date else short
            rel = f"{EVENTS_DIR}/{year}/{stem}"
            groups.setdefault(rel.lower(), []).append((created, eid, rel))
        out = {}
        for members in groups.values():
            members.sort()
            for i, (_c, eid, rel) in enumerate(members):
                out[eid] = f"{rel}.md" if i == 0 else f"{rel} ({eid[3:9]}).md"
        return out

    def render_event(self, eid, rel):
        idx = self.index
        e = idx.event(eid)
        files = idx.event_files(eid)
        parents, subs = idx.effective_categories(eid)
        tags = idx.event_tags(eid)
        date = Path(rel).stem[:10] if re.match(r"\d{4}-\d{2}-\d{2}", Path(rel).stem) else ""

        def uniq(seq):
            out = []
            for v in seq:
                if v and v not in out:
                    out.append(v)
            return out

        cover = next((f["name"] for f in files if f["type"] == "image"), None)
        fm = ["---", f"xolitical_id: {eid}", f"event: {yaml_str(e['name'])}"]
        fm += yaml_list("categories", [self.category_link(c["id"]) for c in parents])
        fm += yaml_list("subcategories", [self.category_link(c["id"]) for c in subs])
        fm += ["tags: []"] if not tags else ["tags:"] + [f"  - {t}" for t in tags]
        fm.append(f"date: {date}" if date else "date:")
        if cover:
            fm.append(f"cover: {yaml_str(f'[[{cover}]]')}")
        fm += yaml_list("accounts", uniq(f["account"] for f in files))
        fm += yaml_list("platforms", uniq(f["platform"] for f in files))
        fm += yaml_list("sources", uniq(f["source"] for f in files))
        fm += yaml_list("added_by", uniq(f["added_by"] for f in files))
        fm.append(f"file_count: {len(files)}")
        fm.append("---")

        body = []
        if parents:
            groups = []
            for p in parents:
                kids = [s for s in subs if s["parent"] == p["id"]]
                g = f"**{self.category_link(p['id'])}**"
                if kids:
                    g += " › " + ", ".join(self.category_link(s["id"]) for s in kids)
                groups.append(g)
            body.append(" · ".join(groups))
        else:
            body.append("*Uncategorized*")
        body.append("")
        for i, f in enumerate(files, 1):
            bits = [str(i)]
            if f["account"]:
                bits.append(f"@{f['account']}" if f["platform"] in ("twitter", "instagram") else f["account"])
            elif f["platform"]:
                bits.append(f["platform"])
            if f["posted"]:
                bits.append(f["posted"])
            if f["source"]:
                bits.append(f"[source]({f['source']})")
            body.append("### " + " · ".join(bits))
            body.append(f"![[{f['name']}]]")
            if (f["note"] or "").strip():
                body.append("")
                body.append(f["note"].strip())
            body.append("")
        body.append(END_LINE)
        body.append("")
        return "\n".join(fm + body)

    def write_event(self, eid, paths=None):
        paths = paths or self.event_paths()
        rel = paths[eid]
        old = self.note_paths.get(eid)
        tail = read_tail(self.vault / (old or rel))
        write_text(self.vault / rel, self.render_event(eid, rel) + tail)
        if old and old != rel:
            self._remove(old)
            self.rewrite_links(old[:-3], rel[:-3])
        self.note_paths[eid] = rel
        return rel

    # ------------------------------------------------------------ link fixes
    def rewrite_links(self, old_rel, new_rel):
        """Point [[old]] / [[full/old/path]] links anywhere in the vault at the new note."""
        old_stem, new_stem = old_rel.rsplit("/", 1)[-1], new_rel.rsplit("/", 1)[-1]
        pat = re.compile(r"\[\[(?:" + re.escape(old_rel) + "|" + re.escape(old_stem) + r")(?=[\]|#])")
        for p in self.vault.rglob("*.md"):
            parts = p.relative_to(self.vault).parts
            if parts and parts[0] in (MEDIA_DIR, ".obsidian", ".xolitical"):
                continue
            try:
                text = p.read_text(encoding="utf-8")
            except OSError:
                continue
            if old_stem not in text:
                continue
            new_text = pat.sub(lambda m: "[[" + (new_rel if "/" in m.group(0) else new_stem), text)
            if new_text != text:
                write_text(p, new_text)

    # ---------------------------------------------------------------- rebuild
    def rebuild_all(self):
        cats = [r["id"] for r in self.index.categories()]
        # parents first so subcategory folders exist under the right name
        cats.sort(key=lambda cid: bool(self.index.category(cid)["parent"]))
        for cid in cats:
            self.write_category(cid)
        paths = self.event_paths()
        for eid in paths:
            self.write_event(eid, paths)
        known = set(cats) | set(paths)
        orphans = [rel for xid, rel in self.note_paths.items() if xid not in known]
        return {"categories": len(cats), "events": len(paths), "orphans": orphans}


# ------------------------------------------------------------------ scaffold
HOME_MD = """# Xolitical

A collaborative archive of political media (screenshots, images, videos and articles from Twitter/X, Instagram, YouTube and Substack), grouped into **named events** and filed under **categories › subcategories**.

## Browse

Open [[Xolitical.base]] for every view: **Gallery** · **Events** · **Categories** · **Needs review** · **Papers**.

![[Xolitical.base#Gallery]]

## How this vault is built

- **Events** (`Events/<year>/`): one note per event. Its category links sit at the top, followed by every media file paired into the event, each with its own note and source link.
- **Categories** (`Categories/`): one note per category and subcategory. Each one lists every event that links to it.
- **Papers** (`Papers/`): scientific papers and primary sources, linked from events.
- Notes in `Events/` and `Categories/` are generated by the Xolitical viewer (`tools/viewer/`) from the index in `.xolitical/`. Text you write **below** the `%% xolitical:end %%` line is preserved; everything above it is regenerated.
- Media files live in `_media/`. That folder is local to each machine and never committed.
"""

XOLITICAL_BASE = """properties:
  note.file_count:
    displayName: Files
  note.date:
    displayName: Date
  note.added_by:
    displayName: Added by
views:
  - type: cards
    name: Gallery
    image: note.cover
    filters:
      and:
        - file.inFolder("Events")
    order:
      - file.name
      - note.categories
      - note.file_count
    sort:
      - property: note.date
        direction: DESC
  - type: table
    name: Events
    filters:
      and:
        - file.inFolder("Events")
    order:
      - file.name
      - note.date
      - note.categories
      - note.subcategories
      - note.tags
      - note.file_count
      - note.accounts
      - note.added_by
    sort:
      - property: note.date
        direction: DESC
  - type: table
    name: Categories
    filters:
      and:
        - file.inFolder("Categories")
    order:
      - file.name
      - note.parent
  - type: table
    name: Needs review
    filters:
      and:
        - file.inFolder("Events")
        - file.hasTag("needs-review")
    order:
      - file.name
      - note.date
      - note.categories
      - note.added_by
  - type: table
    name: Papers
    filters:
      and:
        - file.inFolder("Papers")
    order:
      - file.name
      - note.authors
      - note.year
      - note.added_by
"""

CATEGORY_BASE = """filters:
  and:
    - file.inFolder("Events")
    - file.hasLink(this.file)
properties:
  note.file_count:
    displayName: Files
  note.date:
    displayName: Date
views:
  - type: cards
    name: Gallery
    image: note.cover
    order:
      - file.name
      - note.date
      - note.file_count
    sort:
      - property: note.date
        direction: DESC
  - type: table
    name: Table
    order:
      - file.name
      - note.date
      - note.subcategories
      - note.tags
      - note.file_count
      - note.added_by
    sort:
      - property: note.date
        direction: DESC
"""

PAPERS_README = """# Papers

One note per scientific paper or primary source. Small PDFs can be stored here directly. Otherwise link them by URL or DOI.

Suggested frontmatter:

```yaml
---
title: ""
authors: []
year:
doi: ""
url: ""
added_by: ""
tags: []
---
```

Link papers from an event note **below** its `%% xolitical:end %%` line, for example `Related: [[Smith 2021 - Inflation expectations]]`. The paper's backlinks pane will then list every event that cites it.
"""


def scaffold(vault: Path):
    """Create the vault skeleton. Never overwrites existing files."""
    for d in (EVENTS_DIR, CATEGORIES_DIR, "Papers", MEDIA_DIR):
        (vault / d).mkdir(parents=True, exist_ok=True)
    for rel, text in (("Home.md", HOME_MD), ("Xolitical.base", XOLITICAL_BASE),
                      ("Category.base", CATEGORY_BASE), ("Papers/README.md", PAPERS_README)):
        p = vault / rel
        if not p.exists():
            write_text(p, text)
    app = vault / ".obsidian" / "app.json"
    cfg = {}
    if app.exists():
        try:
            cfg = json.loads(app.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            cfg = {}
    ignore = cfg.get("userIgnoreFilters", [])
    if f"{MEDIA_DIR}/" not in ignore:
        ignore.append(f"{MEDIA_DIR}/")
    cfg.update({
        "userIgnoreFilters": ignore,
        "attachmentFolderPath": MEDIA_DIR,
        "alwaysUpdateLinks": True,
        "useMarkdownLinks": False,
    })
    cfg.setdefault("newLinkFormat", "shortest")
    write_text(app, json.dumps(cfg, indent=2) + "\n")
